/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MastermindGame;

import java.awt.Font;
import java.util.Arrays;

/**
 *
 * @author ctg5117
 */
public class JPGame extends javax.swing.JPanel {
    
    Client client;

    /**
     * Creates new form JPGame
     */
    public JPGame() {
        initComponents();
    }
    
    public JPGame(Client client){
        initComponents();
        this.client = client;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPlayer1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtPlayer2 = new javax.swing.JTextArea();
        jbCheckPhrase = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfFirst = new javax.swing.JTextField();
        jtfSecond = new javax.swing.JTextField();
        jtfThird = new javax.swing.JTextField();
        jtfFourth = new javax.swing.JTextField();
        jtfFifth = new javax.swing.JTextField();
        jlCurrentTurn = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtaCurrentTurn = new javax.swing.JTextArea();
        jlYourPhrase = new javax.swing.JLabel();

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jtPlayer1.setEditable(false);
        jtPlayer1.setColumns(20);
        jtPlayer1.setRows(5);
        jScrollPane1.setViewportView(jtPlayer1);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jtPlayer2.setEditable(false);
        jtPlayer2.setColumns(20);
        jtPlayer2.setRows(5);
        jScrollPane2.setViewportView(jtPlayer2);

        jbCheckPhrase.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbCheckPhrase.setText("Check Phrase");
        jbCheckPhrase.setEnabled(false);
        jbCheckPhrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCheckPhraseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Your Guesses");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Player Two's Guesses");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Enter Phrase:");

        jlCurrentTurn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlCurrentTurn.setText("Current Turn");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jtaCurrentTurn.setEditable(false);
        jtaCurrentTurn.setColumns(20);
        jtaCurrentTurn.setRows(5);
        jScrollPane4.setViewportView(jtaCurrentTurn);

        jlYourPhrase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlYourPhrase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfThird, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfFourth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfFifth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlYourPhrase, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jbCheckPhrase, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                        .addComponent(jlCurrentTurn)
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jScrollPane4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jlCurrentTurn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfFirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfThird, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfFourth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfFifth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlYourPhrase, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jbCheckPhrase, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbCheckPhraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCheckPhraseActionPerformed
        StringBuilder sb = new StringBuilder();
        sb.append(jtfFirst.getText().substring(0, 1).toUpperCase());
        sb.append(jtfSecond.getText().substring(0, 1).toUpperCase());
        sb.append(jtfThird.getText().substring(0, 1).toUpperCase());
        sb.append(jtfFourth.getText().substring(0, 1).toUpperCase());
        sb.append(jtfFifth.getText().substring(0, 1).toUpperCase());
        String strPhrase = sb.toString();
        jtPlayer1.append(strPhrase + "\n");
        char[] charPhrase = strPhrase.toCharArray();
        Phrase phrase = new Phrase(charPhrase);
        client.sendPhrase(phrase);
        jtfFirst.setText("");
        jtfSecond.setText("");
        jtfThird.setText("");
        jtfFourth.setText("");
        jtfFifth.setText("");
    }//GEN-LAST:event_jbCheckPhraseActionPerformed
    
    public void activateButton(){
        jbCheckPhrase.setEnabled(true);
    }
    
    public void disableButton(){
        jbCheckPhrase.setEnabled(false);
    }
    
    public void setYourPhrase(String phrase){
        jlYourPhrase.setText(phrase);
    }
    
    public void updateCurrentTurn(String[] text){
        jtaCurrentTurn.append(Arrays.toString(text) + "\n");
    }
    
    public void updateOpponentGuesses(String guess) {
    	jtPlayer2.append(guess + "\n");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbCheckPhrase;
    private javax.swing.JLabel jlCurrentTurn;
    private javax.swing.JLabel jlYourPhrase;
    private javax.swing.JTextArea jtPlayer1;
    private javax.swing.JTextArea jtPlayer2;
    private javax.swing.JTextArea jtaCurrentTurn;
    private javax.swing.JTextField jtfFifth;
    private javax.swing.JTextField jtfFirst;
    private javax.swing.JTextField jtfFourth;
    private javax.swing.JTextField jtfSecond;
    private javax.swing.JTextField jtfThird;
    // End of variables declaration//GEN-END:variables
}
